hub/urls.py
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import ListView
from . import views


app_name = 'hub'

urlpatterns = [
    path('music/',views.music_page , name= "music_hub" ),
    path('<int:bount_id>',views.bounty_details, name="bountydetails"),
    path('<int:apply_id>/apply',views.apply_bounty, name="bountyapply"),
    path('<int:fund_id>/fund',views.fund_bounty, name="bountyfund"),
    path('submission/',views.application_submission, name='submission'),
    path('like/<int:post_id>', views.toggle_like, name='toggle_like'),
    path('comment/<int:post_id>', views.comment_sub, name="save_comment"),
    
]

#ALLOWS templates to access and display images stored in your models.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

threads/urls.py
from django.urls import path, include 
from django.views.generic import ListView
from .models import Post
from . import views
from hub import urls as hub_urls 


app_name = 'threads'

urlpatterns = [
    path('music/',ListView.as_view(
        queryset = Post.objects.all(),
        template_name ="threads_list.html"
    ),name="threadlist"),
   
]

wonye/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bounties/",include('bounties.urls')),
    path("",include('dashboard.urls')),
    path("hub/", include('hub.urls')),
    path("threads/",include('threads.urls')),
    path("user_auth/",include('user_auth.urls')),
    path("resources/",include('resources.urls')),
]

threads/models.py
from django.db import models
from django.contrib.auth.models import User




# Create your models here.
class Guild(models.Model):
    guild = models.CharField(max_length =150, default ='')

    def __str__(self):
        return self.guild

class Type (models.Model):
    title = models.CharField(max_length =150, default ='')

    def __str__(self):
        return self.title

class Category (models.Model):
    category =models.CharField(max_length =150, default ='')

    def __str__(self):
        return self.category


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  
    guild  = models.ForeignKey(Guild, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    type = models.ForeignKey(Type,on_delete= models.CASCADE)
    category = models.ForeignKey(Category,on_delete= models.CASCADE)

    # Like counter for posts
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)


    def __str__(self):
        return self.title
    
    def total_likes(self):
        return self.likes.count()
    

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  
    post = models.ForeignKey(Post, on_delete=models.CASCADE)  
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)
    

    def __str__(self):
        return f"Comment by {self.user.first_name} on {self.post.title}"
    
    def total_likes(self):
        return self.likes.count()

threads/views.py
from django.shortcuts import render
from .models import Post,Comment 

# Create your views here.

threads/templates/threads_list.html
{% load static %}

<div class="bounty-hub-area">
    <div class="head-bount-con">
        <h3 class="guild-heading">💬THREADS -DISCUSSIONS</h3>
    </div>
   
    <div class="thread-list-con">
        {% for post in threadz %}
        <div class="thread-obj-con">
            <div class="thead-con">
                <h5 class="post-title">{{post.title|upper}}</h5>
            </div>
            <div class="tline-con">
                <div class="tline-dotted"></div>
            </div>
            <div class="thread-par-con">
                <p class="tpar">{{post.content}}</p>
            </div>
            <div class="tlast-line-con">
                <div class="comment-button">

                    <a href="#" id="comment-button">
                        <img src="{% static 'Vector.svg' %}" alt="comment-button"   class="img-comment">
                    </a>
                </div>
                <div class="like-button" id="like-button">
                    {%if user in post.post_likes.all %}
                        <a href="{%url 'hub:toggle_like' post.id%}" class="toggle-like">
                            <div  id="like-butt" class="likecon-con">
                                <p class="likin heart-moji" >&#10084;&#65039;</p>
                            </div>
                            
                        </a>
                    
                    {% else %}
                        <a href="{%url 'hub:toggle_like' post.id%}" class="toggle-like">
                            <div  id="like-butt" class="likecon-con">
                                <img src="{% static 'like.svg' %}" alt="like-button" id="like-butt" class="img-like likin">
                            </div>  
                        </a> 
                    {% endif %}
                    
                </div>
                <div class="cate-con">
                    <div class="cat-box">
                        <p>{{post.category|upper}}</p>
                    </div>
                </div>
                <div class="type-con">
                    <div class="type-box">
                        <p class="typ-text">{{post.type|upper}}</p>
                    </div>
                </div>
                <div class="user-con">
                    <div class="user-box">
                        <p class="user-name">@{{post.user.first_name|lower}}</p>
                    </div>
                </div>
            </div>
            
            <div id="comment-ara"  class="comment-area-con" >
                <div class="comment-input-area">
                    <div class="com-input-con">
                        <form id="post-com-form" action="{%url 'hub:save_comment' post.id %}" method="post">
                            {% csrf_token %}
                            <p>-comment as <span class="user-comm-text">@{{ user.first_name|lower }}</span></p>
                            <div class="content-box-con">{{form.content}}</div>
                            <input type="submit" value="SUBMIT">
                        </form> 
                    </div>
                </div>
                <div class="comment-display-con" id="comment-display">
                    {% for comment in comments %}
                    <div>
                        {% if comment.post == post %}
                        <div class="comment-con">
                            <p class="com-user">@{{ comment.user.first_name|lower }}</p>
                            <div class="content-con">
                                <p class="comm-text">{{ comment.content }}</p>
                            </div>
                            
                        </div>
                        {% endif %}
                       
                    </div>
                    {% endfor %}
                    
                </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Add JavaScript to handle the AJAX request -->
<script>
    $(document).ready(function(){
        $('.toggle-like').click(function (e){
            e.preventDefault();//stop link from going to new page

            // Get the post ID from the link's href attribute 
            var postID = $(this).attr('href').split('/').pop();
            

            $.ajax({
                url: "{%url 'hub:toggle_like' post_id=0 %}".replace(0,postID),
                type: 'GET',
                success: function (respone){
                    if (respone.liked){
                        $('#like-butt').html('<p class="likin heart-moji">&#10084;&#65039;</p>');
                    } else {
                        $('#like-butt').html('<img src="{% static 'like.svg'%}" alt="like-button" id="co" class="img-like likin">');

                    }
                    var urlat = '/hub/toggle_like/' + postID 
                    // Re-add the href attribute
                    $('#like-button a.toggle-like').attr('href', urlat);
                },
                error: function(xhr,errmsg,err) {
                    console.log(xhr.status+":"+xhr.responseText);
                }
            });
        });

    });

    //get comment button ID 

    var comment_icon = document.getElementById("comment-button");
    var comm_area= document.getElementById("comment-ara");

    //on click of icon hide or reveal comment area
    comment_icon.addEventListener("click", function(event){
        if(comm_area.style.display=="none"){
            comm_area.style.display="block";
        }else{
            comm_area.style.display = "none";
        }
    });
</script>