hub/urls.py
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import ListView
from . import views


app_name = 'hub'

urlpatterns = [
    path('music/',views.music_page , name= "music_hub" ),
    path('<int:bount_id>',views.bounty_details, name="bountydetails"),
    path('<int:apply_id>/apply',views.apply_bounty, name="bountyapply"),
    path('<int:fund_id>/fund',views.fund_bounty, name="bountyfund"),
    path('submission/',views.application_submission, name='submission'),
    path('like/<int:post_id>', views.toggle_like, name='toggle_like'),
    path('comment/<int:post_id>', views.comment_sub, name="save_comment"),
    
]

#ALLOWS templates to access and display images stored in your models.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

user_auth/urls.py
from django.urls import path, include 
from . import views
from .views import SignUpView

app_name = 'user_auth'
urlpatterns = [
path('', views.user_login, name='login'),
path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
path("signup/", SignUpView.as_view(), name="signup"),
path('logout/', views.user_logout, name="logout"),
]

wonye/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bounties/",include('bounties.urls')),
    path("",include('dashboard.urls')),
    path("hub/", include('hub.urls')),
    path("threads/",include('threads.urls')),
    path("user_auth/",include('user_auth.urls')),
    path("resources/",include('resources.urls')),
]

templates/header.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
    <HEAD>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link rel="stylesheet" href="{%static 'header.css' %}" >
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </HEAD>
    <body>
        <section class="main_area">
            <div class="content">
                {% block content %}{% endblock %}
            </div>

        </section>

        <footer class="footar">
            <div class="bot_con">
                <p class="t-c">
                    © STUDENT STUDIOS ALL RIGHTS RESERVED.
                </p>
            </div>
        </footer>
    </body>

</html>

templates/object_header.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
    <HEAD>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link rel="stylesheet" href="{%static 'header.css' %}" >
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </HEAD>
    <body>

        <section class="main_area">
            <div class="content_grid">

                <div class="left-side-bar">
                    <header>
                        <div class="odj-header">
                            <h2 class="hd-con obj-con">
                                <div class="logo-con">
                                    <p class="logo">WONYE</p>
                                </div>
                            </h2>
                            <div class="guildhome-con">
                                <a href="{%url 'hub:music_hub' %}">
                                    <p class="guild-home-text">- 🏛️ GUILD HUB</p>
                                </a>
                            </div>
                        </div>
                        
                    </header>
                    <div class="panel-con">
                        {% block panel %}{% endblock %}
                    </div>
                </div>
                <div class="right-main-area">
                    <div class="right-top-ob">
                        <div class="lne-con">
                            <div class="line-lie line-obj"></div>
                        </div>
                        <div class="launch-con">
                            <a href="{%url 'user_auth:logout'%}" class="lan-link">LOGOUT</a>
                        </div>
                    </div>
                    <div class="main_cont_con">
                        {% block content %}{% endblock %}
                    </div> 
                </div>
                
            </div>
            

        </section>

        <footer class="footar">
            <div class="bot_con">
                <p class="t-c">
                    © STUDENT STUDIOS ALL RIGHTS RESERVED.
                </p>
            </div>
        </footer>
    </body>

</html>