bounties/urls.py
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import ListView
from . import views
from hub import urls as hub_urls 
from .models import Bounty

app_name= "bounties"

urlpatterns =[

    path('music/',ListView.as_view(
        queryset = Bounty.objects.all(),
        template_name ="bounty.html"
    ), name="shortbounty"),
    path('hub/', include(hub_urls))
]

#ALLOWS templates to access and display images stored in your models.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hub/urls.py
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import ListView
from . import views


app_name = 'hub'

urlpatterns = [
    path('music/',views.music_page , name= "music_hub" ),
    path('<int:bount_id>',views.bounty_details, name="bountydetails"),
    path('<int:apply_id>/apply',views.apply_bounty, name="bountyapply"),
    path('<int:fund_id>/fund',views.fund_bounty, name="bountyfund"),
    path('submission/',views.application_submission, name='submission'),
    path('like/<int:post_id>', views.toggle_like, name='toggle_like'),
    path('comment/<int:post_id>', views.comment_sub, name="save_comment"),
    
]

#ALLOWS templates to access and display images stored in your models.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

wonye/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bounties/",include('bounties.urls')),
    path("",include('dashboard.urls')),
    path("hub/", include('hub.urls')),
    path("threads/",include('threads.urls')),
    path("user_auth/",include('user_auth.urls')),
    path("resources/",include('resources.urls')),
]

bounties/models.py
from django.db import models

# Create your models here.
class Bounty_category(models.Model):
    category= models.CharField(max_length=150, default='')


    def __str__(self):
        return self.category


class Bounty(models.Model):
    bounty_title= models.CharField(max_length=150, default='')
    location= models.CharField(max_length=150, default='')
    category_choice= models.ForeignKey(Bounty_category, on_delete=models.CASCADE)
    despriction = models.TextField()
    overview = models.TextField()
    responsibilities =models.TextField()
    qualifications =models.TextField()
    inclosing = models.TextField()
    value = models.IntegerField()

    def __str__(self):
        return self.bounty_title
    
class Fund(models.Model):
    fund_title = models.CharField(max_length=150, default='')
    bounty = models.ForeignKey(Bounty, on_delete=models.CASCADE)
    intro = models.TextField()
    overview = models.TextField()
    why_support= models.TextField()
    how_to_help = models.TextField()
    qr_code = models.ImageField(upload_to='donate_qr/')

    def __str__(self):
        return self.fund_title

class ApplicationForm(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    resume = models.FileField(upload_to='uploads/resumes/')
    cover_letter = models.FileField(upload_to='uploads/cover_letters/')
    portfolio = models.FileField(upload_to='uploads/portfolios/', blank=True, null=True)


class Apply(models.Model):
    apply_title = models.CharField(max_length=150, default='')
    bounty = models.ForeignKey(Bounty, on_delete=models.CASCADE)
    intro = models.TextField()
    why_contribute = models.TextField()
    #application form
    
    class Meta:
        verbose_name_plural = "Applications"

bounties/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

bounties/templates/application.html
{% extends "object_header.html" %}
{%load static%}

{% block panel %}
<div class="panel-bount-con">
    <div class="panel-con">
        {% include "bounty.html" %}
    </div>
    
</div>
{% endblock %}


{%block content%}
<div class="main_application_area">
    <div class="right_apply_con par-con">
        <div class="apply-title-con">
            <h5 class="fund-text-head">TITLE <span class="fountain-pen-emoji">&#128395;:</span> </h5>
            <h5 class="head-apply fund-text-head">{{application_info.apply_title}}</h5>
        </div>
        <div class="intro-par-con par-con">
            <p class="par-title par-hd">INTRODUCTION:</p>
            <br>
            <p class="ap-intro-par">{{application_info.intro}}</p>
        </div>
        <div class="why-contrib-con par-con">
            <p class="par-title par-hd">WHY CONTRIBUTE:</p>
            <br>
            <p class="ap-why-par">{{application_info.why_contribute}}</p>
        </div>
         
    </div>

    

    <div class="application-form-con">
        <h5 class="par-hd">APPLY BELOW <span>&#128221;:</span></h5>
        <form action="{%url 'hub:submission'%}" method="post" enctype="multipart/form-data" class="app-form">
            {% csrf_token %}

            {{ form.as_p }}
            <button type="submit" class="sub-button">SUBMIT APPLICATION</button>
        </form>
    </div>
    <br>
    <br>
    <br>

    <!-- The Modal -->
    <div id="myModal" class="modal">
        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <p>Your application has been submitted successfully! <span>&#128512;</span></p>
        </div>
    </div>
    <br>
    <br>
    <br>
    


</div>


  


<script>
  // Get the modal element
  var modal = document.getElementById("myModal");


  // Display the modal when needed
  window.onload = function() {
      var success = "{{ success }}";
      if (success === "True") {
          modal.style.display = "block";
      }
      else {
        modal.style.display = "none"
      }
  }

  // Get the close button
  var closeButton = document.getElementsByClassName("close")[0];

  // Close the modal when the close button is clicked
  closeButton.onclick = function() {
      modal.style.display = "none";
  }

  // Close the modal if the user clicks outside of it
  window.onclick = function(event) {
      if (event.target == modal) {
          modal.style.display = "none";
      }
  }
</script>
{% endblock%}

bounties/templates/bounty.html
<div class="bounty-hub-area">
    <div class="head-bount-con">
        <h3 class="guild-heading">💰GUILD BOUNTIES</h3>
    </div>
    <div class="bounty-par-con">
        <p>GUILD BOUNTIES ARE A WAY IN WHCH COMMUNITIES/GUILDS CAN BUILD A HIGH QUALITY RESOURCE LIBRARY BY ENGAGING WITH EXPERTS.</p>
    </div>
    <div class="bounty-list-con">
        {% for bount in bounties %}
        <div class="bount-obj-con">
            <div class="top-bount-con">
                <p class="bont">BOUNTY</p>
                <div class="line-bount"></div>
            </div>
            <div class="title-bount-con">
                <p class="bount-title"><a href="{%url 'hub:bountydetails' bount.id %} " class="bount-title">{{bount.bounty_title}}</a></p>
            </div>
            <div class="button-bount-con">
                {% for apply in bount.apply_set.all %}
                <button class="button-mainstyle butt-apply"><a href="{%url 'hub:bountyapply' apply.id %}">APPLY</a></button>
                {% endfor %}
                {% for fund in bount.fund_set.all %}
                <button class="button-mainstyle butt-fund"><a href="{%url 'hub:bountyfund' fund.id %}">$FUND</a></button>
                {% endfor %}
                <button class="button-mainstyle butt-cat"><a href="#">{{bount.category_choice|upper }}</a></button>
                
            </div>
        </div>
        {% endfor %}
    </div>
</div>

bounties/templates/bounty_details.html
{% extends "object_header.html" %}
{%load static%}

{% block panel %}
<div class="panel-bount-con">
    <div class="panel-con">
        {% include "bounty.html" %}
    </div>
    
</div>
{% endblock %}


{%block content%}
<div class="main_bount_area">
    <div class="left_bount_con"></div>
    <div class="right_bount_details">
        <div class="sec-con">
            <h5 class="fund-text-head"><span class="fountain-pen-emoji">&#128395;</span> TITLE: </h5>
            <h5 class="fund-text-head">{{bounty_dets.bounty_title|upper}}</h5>
        </div>
        
        <div class="sec-con">
            <p class="par-title par-hd">📍LOCATION:</p>
            <p>{{bounty_dets.location}}</p>
        </div>
        
        <div class="sec-con">
            <p class="par-title par-hd">📃 DESCRIPTION:</p>
                <br>
            <p>{{bounty_dets.despriction}}</p>
        </div>
        
        <div class="sec-con">
            <p class="par-title par-hd">- OVERVIEW:</p>
                <br>
            <p>{{bounty_dets.overview}}</p>
        </div>
        
        <div class="sec-con">
            <p class="par-title par-hd">- RESPONSIBILITIES:</p>
                <br>
            <p>{{bounty_dets.responsibilities}}</p>
        </div>
        
        <div class="sec-con">
            <p class="par-title par-hd">- QUALIFICATIONS:</p>
                <br>
            <p>{{bounty_dets.qualifications}}</p>
        </div>
        
        <div class="sec-con">
            <br>
            <p>{{bounty_dets.inclosing}}</p>
        </div>
        
        <div class="sec-con">
            <p class="par-title par-hd">💎BOUNTY VALUE:</p>
            <p>R {{bounty_dets.value}}</p>
        </div>
        
    </div>

    <div class="button-bount-con">
        {% for apply in bounty_dets.apply_set.all %}
        <button class="button-mainstyle butt-apply"><a href="{%url 'hub:bountyapply' apply.id %}">APPLY</a></button>
        {% endfor %}
        {% for fund in bounty_dets.fund_set.all %}
        <button class="button-mainstyle butt-fund"><a href="{%url 'hub:bountyfund' fund.id %}">$FUND</a></button>
        {% endfor %}
        
    </div>
    <br>
    <br>
    <br>

</div>



{% endblock%}

bounties/templates/fund_bounty.html
{% extends "object_header.html" %}
{%load static%}

{% block panel %}
<div class="panel-bount-con">
    <div class="panel-con">
        {% include "bounty.html" %}
    </div>
    
</div>
{% endblock %}

{%block content%}
<div class="main_fund_area">
    <div class="right_fund_con">
        <div class="fund-head">
            <h5 class="fund-text-head"><span class="fountain-pen-emoji">&#128395;</span>TITLE:</h5>
            <h5 class="fund-text-head"> {{fund_info.fund_title|upper}}</h5>
        </div>
        
        <div class="fund-par-cons">
            <div class="intro-fund-con ">
                <p class="par-title par-hd">📃INTRODUCTION:</p>
                <br>
                <p class="fun-par">{{fund_info.intro}}</p>
            </div>
            <div class="overview-fund-con">
                <p class="par-title par-hd">- OVERVIEW:</p>
                <br>
                <p class="fun-par">{{fund_info.overview}}</p>
            </div>
            <div class="whysupp-fund-con">
                <p class="par-title par-hd">- WHY YOUR SUPPORT MATTERS:</p>
                <br>
                <p class="fun-par">{{fund_info.why_support}}</p>
            </div>
            <div class="help-fund-con">
                <p class="par-title par-hd">- HOW YOU CAN HELP:</p>
                <br>
                <p class="fun-par">{{fund_info.how_to_help}}</p>
            </div>
        </div>
        
        <div class="dontae-head-con">
            <p class="donate-text par-hd">💸 DONATE BELOW AND PART OF THIS EXCITING INITIATIVE:</p>
        </div>
        <div class="pmt-methods-con">
            <div class="pmt-method-grid">
               
                <div class="img-qrcode-con">
                    <img src="{{fund_info.qr_code.url}}" alt="{{fund_info.image.title}}" class="img-fund-qr">
                </div>
                <div class="cs-pmts-con">
                    <div class="cs-con">
                        <p>COMING SOON!</p>
                    </div>
                    <div class="top-layer-pmt">
                        <img src="{%static 'images/payment/🦆 icon _visa line_.png'%}" alt="visa-logo" class="img-visa">
                        <img src="{%static 'images/payment/🦆 icon _apple fill_.png'%}" alt="apple-logo" class="img-apple">
                        <img src="{%static 'images/payment/🦆 icon _google fill_.png'%}" alt="google-logo" class="img-google">
                    </div>
                    <div class="bottom-layer-pmt">
                        <img src="{%static 'images/payment/logosnapscan.png'%}" alt="snapsacn-logo" class="img-snap">
                        <img src="{%static 'images/payment/polygonLogo 1.png'%}" alt="polygon-logo" class="img-polygon">
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>

{% endblock%}