dashboard/urls.py
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import ListView, DetailView
from . import views
from .models import Thumbnail

app_name = "dashboard"

urlpatterns =[
    path('',views.index, name="landing"),
    path('discover/',ListView.as_view(
        queryset= Thumbnail.objects.all(),
        template_name ="thumbnails.html"
        
    ),name= "discover",),
    path('<int:thumbnail_id>/',views.thumb_link, name="guildpage"),
]

#ALLOWS templates to access and display images stored in your models.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hub/urls.py
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import ListView
from . import views


app_name = 'hub'

urlpatterns = [
    path('music/',views.music_page , name= "music_hub" ),
    path('<int:bount_id>',views.bounty_details, name="bountydetails"),
    path('<int:apply_id>/apply',views.apply_bounty, name="bountyapply"),
    path('<int:fund_id>/fund',views.fund_bounty, name="bountyfund"),
    path('submission/',views.application_submission, name='submission'),
    path('like/<int:post_id>', views.toggle_like, name='toggle_like'),
    path('comment/<int:post_id>', views.comment_sub, name="save_comment"),
    
]

#ALLOWS templates to access and display images stored in your models.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

user_auth/urls.py
from django.urls import path, include 
from . import views
from .views import SignUpView

app_name = 'user_auth'
urlpatterns = [
path('', views.user_login, name='login'),
path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
path("signup/", SignUpView.as_view(), name="signup"),
path('logout/', views.user_logout, name="logout"),
]

wonye/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bounties/",include('bounties.urls')),
    path("",include('dashboard.urls')),
    path("hub/", include('hub.urls')),
    path("threads/",include('threads.urls')),
    path("user_auth/",include('user_auth.urls')),
    path("resources/",include('resources.urls')),
]

dashboard/models.py
from django.db import models

# Create your models here.

    
class Guild_status(models.Model):
    
    status= models.CharField(max_length=150, default="select")

    def __str__(self):
        return self.status
 




class Thumbnail(models.Model):
    thumbnail_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150, )
    guild_text = models.CharField(max_length=150, default="MAKERS GUILD")
    #Guild category choice dropdown
    category_text = models.CharField(max_length=150, default='')

    #GUILD status choice 
    status = models.ForeignKey(Guild_status, on_delete=models.CASCADE)

    image = models.ImageField(upload_to='thumbnails/')

dashboard/views.py
from django.shortcuts import render
from .models import Thumbnail
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


# Create your views here.

def index(request):
    return render(request, 'launch.html')


def thumb_link(request, thumbnail_id):
    '''get thumbnail category and redirect
      to the appropriate page hub ie music hub
    '''
    thumbnail = get_object_or_404(Thumbnail,pk=thumbnail_id)
    thumb_cat = thumbnail.category_text.lower()

    if thumb_cat == "music":
        return HttpResponseRedirect(reverse('hub:music_hub'))
    else:
        context ={
            'thumb_cat': thumb_cat,
        }
        return render(request, 'comingsoon.html', context)
    

dashboard/templates/discover_home.html
{%extends 'header.html'%}
{% load static %}

{% block content %}

<header>
    <hd class="hd-con">
        <div class="logo-con">
            <p class="logo">WONYE</p>
        </div>
        <div class="search-con">
            <div class="search-bar">
                <p class="search-text"></p>
            </div>
        </div>
        <div class="welcome-con">
            <a href="{%url 'user_auth:logout'%}" class="lan-link">LOGOUT</a>
        </div>
  
</header>

<div class="content-discov">
    <div class="cs-box-con">
        <div class="comingsoon-area">
            <div class="csoon-con">
                <p class="flt-text">COMING SOON! ------- (CATEGORY FILTERS)</p>
            </div>
            <div class="filtr-con  music-con">
                <p class="flt-text">MUSIC</p>
            </div>
            <div class="filtr-con tiktok-con">
                <p class="flt-text">TIKTOK</p>
            </div>
            <div class="filtr-con yt-con">
                <p class="flt-text">YOUTUBE</p>
            </div>
            <div class="filtr-con twitt-con">
                <p class="flt-text">X-(TWEETS)</p>
            </div>
            <div class="filtr-con business-con">
                <p class="flt-text">BUSINESS</p>
            </div>
            <div class="filtr-con finance-con">
                <p class="flt-text">FINANCE</p>
            </div>
        </div>
    </div>
    
    
    <div class="discov-area">
        <div class="dicov-text-con">
            <h2 class="discov-head">DISCOVER COMMUNITIES</h2>
            <p class="discrip-text">JOIN A COMMUNITY OF CREATORS ,ASK QUESTIONS, GET INSIGHTS, CONTRIBUTE AND PARTICIPATE IN COMMUNITY JAMS.</p>
    
        </div>
        <div class="thumbnail-con">
            {% block thumbnail_area %} {% endblock %}
            <div class="img-x-con">
                <img src="{%static 'images/ximage.png' %}" alt="x-image" class="img-x-icon">
            </div>
        </div>
    </div>
</div>




<div class="trending-area">
    {% block trending_area %} {% endblock %}
</div>



{% endblock %}

dashboard/templates/launch.html
{% extends 'header.html' %}
{% load static %}
{% block content %}
<header>
    <hd class="hd-con">
        <div class="logo-con">
            <p class="logo">WONYE</p>
        </div>
        <div class="lne-con">
            <div class="line-lie"></div>
        </div>
        <div class="launch-con">
            <a href="{% url 'user_auth:login'%}" class="lan-link">LAUNCH!</a>
        </div>
    </hd>
</header>

<section class="main-body">
    <div class="para-con">
        <div class="f-sen">
            <p class="lan-text f-line">A NEW WAY T <span ><img src="{% static 'images/flwrone.png' %}" alt="ytk-design"class="FL-O"></span> DO COMMUNITY</p>
        </div>
        <div class="ttf-sen">
            <div class="ttf-grid">
                <div class="girlpic"><img src="{%static 'images/girl.png' %}" alt="girl" class="img-girl"></div>
                <p class="lan-text snd-line">NEW IDEAS <span><img src="{%static 'images/Arrow 1.png' %}" alt="arrow" class="img-Arrone"></span> RESOURCES</p>
                <p class="lan-text thrd-line">OPENSOURCE CULTURE</p>
                <div class="forth-line">
                    <p class="lan-text frth-line">F </p>
                    <div class="cure-square"></div> 
                    <p class="lan-text frth-line"> R MAKERS <span><img src="{% static 'images/flwrtwo.png' %}" alt="ytk-flower" class="img-fltwo "></span> DOERS</p>
                    
                </div>
                
                <div class="guys-pic"><img src="{%static 'images/guys.png' %}" alt="guys" class="img-guys"></div>
            </div>
        </div>
        <div class="l-sen">
            <p class="lan-text fth-line">CREATOR[S] <span><img src="{%static 'images/Arrow 2.png' %}" alt="arrow" class="red-arrow"></span> JOIN A GUILD</p>
        </div>
    </div>

</section>
{% endblock %}

dashboard/templates/thumbnails.html
{% extends 'discover_home.html' %}
{% load static %}

{% block thumbnail_area  %}

<div class="thumbs-con">
    {% for thumbnail in object_list %}
    <div class="comm-con">
        <div class="thumbn-con">
            <a href="{%url 'dashboard:guildpage' thumbnail.thumbnail_id %}">
                <div class="thumb-text-con">
                    <h3 class="thumb-head">{{thumbnail.title}}</h3>
                    <p class="thumb-par">{{thumbnail.guild_text}}</p>
                    <div class="thumb-line"></div>
                </div>
                <img src="{{thumbnail.image.url}}" alt="{{thumbnail.image.title}} " class="img-thumb">
                <div class="overlay"></div>
            </a>
        </div>
        {%if thumbnail.status|lower == "online" %}
        <div class="stat-con">
            <div class="stat-box-on">
                <p class="stat-text">{{thumbnail.status}}</p>
            </div>
            
        </div>
        {% else %}
        <div class="stat-con">
            <div class="stat-box">
                <p class="stat-text">{{thumbnail.status}}</p>
            </div>
            
        </div>
        {% endif %}

    </div>
   
    {% endfor %}
</div>










{% endblock %}